# Site settings
title: randomPoison
email: dlegare.1001@gmail.com
description: >-
  David's personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: https://randompoison.github.io
twitter_username: randomPoison
github_username:  randomPoison

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji
